[versions]
kotlin = "2.3.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.9.0"

compose = "1.12.0"
compose-material = "1.4.0"
material-symbols = "1.1.6"

logback = "1.6.3"
slf4j = "2.0.18"
kotlin-logging = "7.0.5"

mockk = "1.13.8"
kotest = "6.0.7"

versions-plugin = "0.48.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",  version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test     = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test",  version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json  = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

compose-material = { module = "androidx.compose.material3:material3", version.ref = "compose-material" }
compose-material-symbols = { module = "dev.vicart:compose-material-symbols", version.ref = "material-symbols" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
jvm-testing = [
    "mockk",
    "kotlin-test",
    "kotest-assertions",
    "kotest-property",
    "kotest-runner-junit"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
